### ISSUE TITLE
Line Height Investigation

### ISSUE THREAD

**Issue by chillbrodev** [Supernova-Studio/exporter-flutter#10]
Upon trying out the new exporter this morning after the Line Height changes came in, I noticed some seriously inflated height properties.  I investigated the `text_styles.pr` code and found the correct calculation under the condition `if typographyToken.value.lineHeight.unit == "Pixels"` but the lineHeight value that is being used is incorrect. 

In the image below we have selected the Typography of `M3/Headline/LG/bold` which shows as `60px` under the `Typography Section` with a `48px` font size. 

Then if we review the `Code` section and select the `Table` view (which is shown in the screenshot) we see two `Line Heights`, a `60px` and a `125%`.  

It seems when Supernova parses this it selects the Pixels unit but uses the `125%` value instead which causes the calculation to be `125/48=2.604...` instead of the correct calculation of `60/48=1.25`. 

Not sure how we can remedy this to use the proper value and if this is an issue with Figma or Supernova. Happy to provide more information and schedule a technical call if needed. 

Exported TextStyle for selected Typography in the image below:
```
  static const m3HeadlineLgBold = TextStyle(
    fontFamily: "Industry",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 48,
    decoration: TextDecoration.none,
    letterSpacing: -0.96,
    height: 2.6041666666666665,
    leadingDistribution: TextLeadingDistribution.even,
  );
  ```

<img width="849" alt="image" src="https://user-images.githubusercontent.com/2694785/203408369-92b77c96-075f-4012-a7b9-977871986f9f.png">

**Comment by chillbrodev** [comment]
@JiriTrecak Wanted to highlight this investigation for you to review regarding the new line height addition.

**Comment by Ydus** [comment]
@chillbrodev Hey 👋 thanks for the report. It has been fixed now 🙂

**Comment by chillbrodev** [comment]
@Ydus Confirmed, I ran the importer and the `heights` were correct. Thanks for the fix!
