### ISSUE TITLE
Empty flutter code at exportation

### ISSUE THREAD

**Issue by EArminjon2** [Supernova-Studio/exporter-flutter#4]
Hello,

I tried to export my design (two simple pages) to flutter using supernova cloud :

My figma :
<img width="1440" alt="Capture d’écran 2021-11-10 à 09 41 18" src="https://user-images.githubusercontent.com/92172436/141079349-724749be-077a-4c0f-8c2c-8f09493eaaa0.png">

Figma imported in Super Nova :
<img width="1431" alt="Capture d’écran 2021-11-09 à 17 01 05" src="https://user-images.githubusercontent.com/92172436/140959483-246604b8-2e84-4b79-b412-cf7e35b396c5.png">

Flutter plugin in Super Nova :
<img width="1362" alt="Capture d’écran 2021-11-09 à 17 06 45" src="https://user-images.githubusercontent.com/92172436/140960499-9930c6fe-73af-4256-9628-ba113f4f966b.png">

Build with Super Nova flutter plugin
<img width="1266" alt="Capture d’écran 2021-11-09 à 17 02 56" src="https://user-images.githubusercontent.com/92172436/140959812-a5f0c9f5-827e-46f3-b4b7-19abcb508d0a.png">

Content of the build :
<img width="759" alt="Capture d’écran 2021-11-09 à 17 02 00" src="https://user-images.githubusercontent.com/92172436/140959651-3f5d80c5-5af3-4624-b7c2-55ffe8ac7267.png">

When inspectig flutter output directly on supernova : 
<img width="904" alt="Capture d’écran 2021-11-09 à 17 19 43" src="https://user-images.githubusercontent.com/92172436/140962949-6075a265-b7fa-4e0d-aba1-4b0a7eab679a.png">

Didn't understand why it's empty... Didn't this components files...

Can you help me please <3 ?

**Comment by jan-supernova** [comment]
Hey  EA-YOUHOU,
As of now, Cloud exporters are exporting only Token data with Components coming later. Your exported files appear to be empty. Do you have any Tokens in your Design System?

Have a wonderful day!
Jan, Supernova Team

**Comment by EA-YOUHOU** [comment]
I've imported my project Figma into SuperNova but i didn't see any tokens.

<img width="1435" alt="Capture d’écran 2021-11-10 à 09 39 06" src="https://user-images.githubusercontent.com/92172436/141078977-974fc93a-e3f8-4b5b-9ae5-75f82108c3eb.png">
<img width="1440" alt="Capture d’écran 2021-11-10 à 09 40 06" src="https://user-images.githubusercontent.com/92172436/141079140-42270279-21f0-4001-8cef-a818418e47f6.png">

**Comment by jan-supernova** [comment]
Hey EA-YOUHOU,
From looking at your Figma screenshot, it appears that you do not have any styles in your Figma file, so Supernova has no Tokens to import. If this is the case, this page from our Documentation should explain the whole process to you - https://learn.supernova.io/design-systems/figma/import. 

Have a wonderful day!
Jan, Supernova Team
