### ISSUE TITLE
Height is missing from Text Styles

### ISSUE THREAD

**Issue by chillbrodev** [Supernova-Studio/exporter-flutter#8]
Hello, We have noticed that the property `height` is not coming in correctly. Flutter defines line-height as `height` and the calculation is "line-height/font-size". I have had to manually do the calculations and include them. Is this something that can be added to the exporter?

**Comment by chillbrodev** [comment]
This is an issue that seems to be resolved by two open PRS #5 & #7

**Comment by jan-supernova** [comment]
Hey chillbrodev! PRs were merged, so you should get the proper `height` property in the exporter code now. Publicly available exporter was updated by us. Thank you for bringing this up!

Jan, Supernova Team
